---
resources:
 - name: deploy_app
   type: cf
   source:
    api: {{cf-api}}
    username: {{cf-username}}
    password: {{cf-password}}
    organization: {{cf-organization}}
    space: {{cf-space}}
    skip_cert_check: true
jobs:
- name: sample-app
  serial: true
  plan:
  - get: sample-app
    trigger: true
  - put: deploy_app
    params:
      manifest: sample-app/manifest.yml
      path: sample-app
