resources:
  - name: sample-app
    type: git
    source:
      uri: https://github.com/VijayalakshmiKumar02/sample-app.git
      branch: master
  - name: deploy_app
    type: cf
    source:
     api: https://api.run.pivotal.io
     username: vijayalakshmikumar22@gmail.com
     password: Kalp@ana22
     organization: viji
     space: development
jobs:
  - name: sample-app
    plan:
     - get: sample-app
       trigger: true
     - put: deploy_app
       params:
        manifest: sample-app/manifest-ci.yml
        path: sample-ap
