---
resources:
 - name: sample-app
    type: git
    source:
      uri: https://github.com/VijayalakshmiKumar02/sample-app.git
      branch: master
 - name: deploy_app
  type: cf
  source:
    api: {{cf-api}}
    username: {{cf-username}}
    password: {{cf-password}}
    organization: {{cf-organization}}
    space: {{cf-space}}
    skip_cert_check: true
jobs:
- name: sample-app
  serial: true
  plan:
  - {get:sample-app, trigger: true}
  - put: sample-app
    params:
      manifest: sample-app/manifest.yml
      path: sample-app
